'use strict';

/**
 * cs-doodle 낙서 오브젝트 라이브러리 빌더.
 *
 * 각 오브젝트를 rough.js로 한 번만 결정적으로 그려서 assets/doodle/objects/sprite.svg에
 * <symbol>로 굽는다. 색은 stroke='currentColor'로 남겨 두므로, 실제 색은 호출부의
 * <use class="k-a">가 CSS로 입힌다 (cs-v2의 class="k-a" fill="currentColor" 관례와 동일).
 * seed가 고정돼 있어 같은 오브젝트는 덱 전체에서 항상 같은 손글씨체로 보인다.
 *
 *   node scripts/doodle/build-objects.js
 */
const fs = require('fs');
const path = require('path');
const R = require('./rough-svg.js');
const PEN = require('./pen-style.js');

const OUT = path.join(__dirname, '..', '..', 'assets', 'doodle', 'objects', 'sprite.svg');

const outline = (seed) => ({ seed, roughness: PEN.roughness, bowing: PEN.bowing, stroke: 'currentColor', strokeWidth: PEN.strokeWidth, fill: 'none' });
const dot = (seed) => ({ seed, roughness: PEN.roughness * 0.7, bowing: PEN.bowing, stroke: 'none', fill: 'currentColor', fillStyle: 'solid' });

const OBJECTS = {
  key: (s) => `
    ${R.circle(34, 60, 36, outline(s))}
    ${R.circle(34, 60, 16, outline(s + 1))}
    ${R.line(52, 60, 100, 60, outline(s + 2))}
    ${R.line(80, 60, 80, 72, outline(s + 3))}
    ${R.line(96, 60, 96, 78, outline(s + 4))}
  `,
  lock: (s) => `
    ${R.rectangle(30, 55, 60, 48, outline(s))}
    ${R.arc(60, 55, 46, 52, Math.PI, 2 * Math.PI, false, outline(s + 1))}
    ${R.circle(60, 84, 12, outline(s + 2))}
  `,
  envelope: (s) => `
    ${R.rectangle(15, 35, 90, 60, outline(s))}
    ${R.linearPath([[15, 35], [60, 72], [105, 35]], outline(s + 1))}
  `,
  laptop: (s) => `
    ${R.rectangle(25, 25, 70, 48, outline(s))}
    ${R.polygon([[15, 80], [105, 80], [92, 92], [28, 92]], outline(s + 1))}
  `,
  server: (s) => `
    ${R.rectangle(30, 15, 60, 90, outline(s))}
    ${R.line(40, 40, 80, 40, outline(s + 1))}
    ${R.line(40, 60, 80, 60, outline(s + 2))}
    ${R.line(40, 80, 80, 80, outline(s + 3))}
  `,
  'db-cylinder': (s) => `
    ${R.ellipse(60, 30, 64, 20, outline(s))}
    ${R.line(28, 30, 28, 90, outline(s + 1))}
    ${R.line(92, 30, 92, 90, outline(s + 2))}
    ${R.arc(60, 90, 64, 20, 0, Math.PI, false, outline(s + 3))}
  `,
  cloud: (s) => R.path(
    'M20 75 a18 18 0 0 1 3 -28 a22 22 0 0 1 42 -5 a17 17 0 0 1 22 26 a14 14 0 0 1 -5 8 Z',
    outline(s)
  ),
  gear: (s) => {
    let out = R.circle(60, 60, 52, outline(s)) + R.circle(60, 60, 20, outline(s + 1));
    for (let i = 0; i < 8; i++) {
      const a = (i / 8) * Math.PI * 2;
      const x1 = 60 + 26 * Math.cos(a), y1 = 60 + 26 * Math.sin(a);
      const x2 = 60 + 34 * Math.cos(a), y2 = 60 + 34 * Math.sin(a);
      out += R.line(x1, y1, x2, y2, outline(s + 2 + i));
    }
    return out;
  },
  magnifier: (s) => `
    ${R.circle(46, 46, 56, outline(s))}
    ${R.line(66, 66, 94, 94, outline(s + 1))}
  `,
  check: (s) => R.path('M28 62 L50 84 L94 34', outline(s)),
  x: (s) => `
    ${R.line(30, 30, 90, 90, outline(s))}
    ${R.line(90, 30, 30, 90, outline(s + 1))}
  `,
  exclamation: (s) => `
    ${R.line(60, 20, 60, 75, outline(s))}
    ${R.circle(60, 96, 12, dot(s + 1))}
  `,
  question: (s) => `
    ${R.path('M40 35 C40 15 85 15 85 40 C85 60 60 55 60 75', outline(s))}
    ${R.circle(60, 96, 12, dot(s + 1))}
  `,
  sparkle: (s) => R.polygon(
    [[60, 8], [70, 48], [112, 60], [70, 72], [60, 112], [50, 72], [8, 60], [50, 48]],
    outline(s)
  ),
  'paint-drop': (s) => R.path('M60 18 C85 55, 82 100, 60 100 C38 100, 35 55, 60 18 Z', outline(s)),
  brush: (s) => `
    ${R.line(60, 15, 60, 68, outline(s))}
    ${R.rectangle(48, 65, 24, 14, outline(s + 1))}
    ${R.polygon([[46, 79], [74, 79], [66, 105], [54, 105]], outline(s + 2))}
  `,
  blender: (s) => `
    ${R.rectangle(50, 10, 20, 8, outline(s))}
    ${R.polygon([[38, 18], [82, 18], [72, 92], [48, 92]], outline(s + 1))}
    ${R.path('M82 32 C94 36, 94 56, 82 60', outline(s + 2))}
    ${R.rectangle(34, 92, 52, 16, outline(s + 3))}
  `,
};

function main() {
  const symbols = Object.entries(OBJECTS)
    .map(([name, draw], i) => `  <symbol id="doodle-${name}" viewBox="0 0 120 120">${draw(i * 20 + 1)}</symbol>`)
    .join('\n');
  const svg = `<!-- GENERATED by scripts/doodle/build-objects.js: 직접 고치지 말고 빌더를 수정한 뒤 다시 생성할 것 -->\n<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n${symbols}\n</svg>\n`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, svg);
  console.log(`cs-doodle: ${Object.keys(OBJECTS).length} object symbols written to ${OUT}`);
}

if (require.main === module) main();

module.exports = { OBJECTS };
